default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_beginners_exam_development

test:
  <<: *default
  database: rails_beginners_exam_test

production:
  <<: *default
  database: rails_beginners_exam_production
  username: rails_beginners_exam
  password: <%= ENV['RAILS_BEGINNERS_EXAM_DATABASE_PASSWORD'] %>
